package main

import (
	"archive/zip"
	"bytes"
	"context"
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"io/fs"
	"log"
	"mime"
	"net"
	"net/http"
	neturl "net/url"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"time"
)

// runtime.zip is generated by tools/build-windows.mjs and removed after each build.
//
//go:embed runtime.zip
var runtimeZip []byte

const defaultAddress = "127.0.0.1:17401"
const buildID = "covenant-library-v2.0.0"

var platformJS = []byte(`(function(){
  "use strict";
  function request(method, url, body) {
    var xhr = new XMLHttpRequest();
    xhr.open(method, url, false);
    if (body != null) xhr.setRequestHeader("Content-Type", "text/plain;charset=utf-8");
    xhr.send(body == null ? null : String(body));
    return xhr;
  }
  window.CovenantNativeStorage = {
    getItem: function(key) {
      var xhr = request("GET", "/__covenant/storage?key=" + encodeURIComponent(key));
      return xhr.status === 200 ? xhr.responseText : null;
    },
    setItem: function(key, value) {
      var xhr = request("PUT", "/__covenant/storage?key=" + encodeURIComponent(key), value);
      if (xhr.status !== 204) throw new Error("Unable to save Covenant Library user data.");
    }
  };
  window.CovenantNativeFiles = {
    saveText: function(filename, text) {
      var xhr = request("POST", "/__covenant/export?filename=" + encodeURIComponent(filename), text);
      if (xhr.status !== 200) throw new Error("Unable to export text.");
      return xhr.responseText;
    }
  };
  window.CovenantNativeApplication = {
    canClose: true,
    closeApplication: function() {
      var xhr = request("POST", "/__covenant/quit");
      if (xhr.status !== 200) throw new Error("Unable to close Covenant Library.");
      return true;
    }
  };
  async function aiJSON(url, options) {
    var response = await fetch(url, options || {});
    var payload = null;
    try { payload = await response.json(); } catch (_) {}
    if (!response.ok) throw new Error((payload && payload.error) || "Local AI request failed.");
    return payload || {};
  }
  window.CovenantLocalAI = {
    status: function() { return aiJSON("/__covenant/ai/status"); },
    listModels: function() { return aiJSON("/__covenant/ai/status"); },
    ask: function(payload) {
      return aiJSON("/__covenant/ai/ask", {
        method: "POST",
        headers: {"Content-Type": "application/json"},
        body: JSON.stringify(payload || {})
      });
    }
  };
})();`)

type aiContextItem struct {
	ID    string `json:"id"`
	Kind  string `json:"kind"`
	Title string `json:"title"`
	Text  string `json:"text"`
}

type aiAskRequest struct {
	Question string          `json:"question"`
	Model    string          `json:"model"`
	Context  []aiContextItem `json:"context"`
}

type ollamaTagsResponse struct {
	Models []struct {
		Name  string `json:"name"`
		Model string `json:"model"`
	} `json:"models"`
}

type ollamaGenerateResponse struct {
	Response string `json:"response"`
}

func ollamaAPIBase() string {
	value := strings.TrimSpace(os.Getenv("COVENANT_OLLAMA_URL"))
	if value == "" {
		return "http://127.0.0.1:11434/api"
	}
	u, err := neturl.Parse(value)
	if err != nil || !strings.EqualFold(u.Scheme, "http") {
		return "http://127.0.0.1:11434/api"
	}
	host := strings.ToLower(strings.TrimSpace(u.Hostname()))
	if host != "127.0.0.1" && host != "localhost" && host != "::1" {
		return "http://127.0.0.1:11434/api"
	}
	u.RawQuery = ""
	u.Fragment = ""
	p := strings.TrimSuffix(u.Path, "/")
	if p == "" {
		p = "/api"
	} else if !strings.HasSuffix(p, "/api") {
		p += "/api"
	}
	u.Path = p
	return strings.TrimSuffix(u.String(), "/")
}

func ollamaModels(ctx context.Context) ([]string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, ollamaAPIBase()+"/tags", nil)
	if err != nil {
		return nil, err
	}
	client := &http.Client{Timeout: 2500 * time.Millisecond}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("Ollama did not return its installed models")
	}
	var payload ollamaTagsResponse
	if err := json.NewDecoder(io.LimitReader(resp.Body, 2<<20)).Decode(&payload); err != nil {
		return nil, err
	}
	models := make([]string, 0, len(payload.Models))
	seen := map[string]bool{}
	for _, item := range payload.Models {
		name := strings.TrimSpace(item.Name)
		if name == "" {
			name = strings.TrimSpace(item.Model)
		}
		if name != "" && !seen[name] {
			seen[name] = true
			models = append(models, name)
		}
	}
	return models, nil
}

func preferredModel(models []string) string {
	for _, model := range models {
		if strings.EqualFold(model, "llama3.2:3b") {
			return model
		}
	}
	if len(models) > 0 {
		return models[0]
	}
	return ""
}

func modelInstalled(models []string, wanted string) bool {
	for _, model := range models {
		if model == wanted {
			return true
		}
	}
	return false
}

func buildStudyPrompt(question string, contextItems []aiContextItem) (string, []string) {
	var b strings.Builder
	b.WriteString("You are the optional local study assistant for Covenant Library. Answer only from the supplied local Covenant Library context. Distinguish scripture/library text from secondary Study material. Cite source IDs in square brackets, for example [KJV:Gen:1:1]. If the context does not support an answer, say that clearly. Do not invent quotations, sources, or citations.\n\nQUESTION:\n")
	b.WriteString(strings.TrimSpace(question))
	b.WriteString("\n\nLOCAL CONTEXT:\n")
	ids := make([]string, 0, len(contextItems))
	total := 0
	for index, item := range contextItems {
		if index >= 24 || total >= 36000 {
			break
		}
		id := strings.TrimSpace(item.ID)
		text := strings.TrimSpace(item.Text)
		if id == "" || text == "" {
			continue
		}
		if len(text) > 5000 {
			text = text[:5000]
		}
		if total+len(text) > 36000 {
			text = text[:max(0, 36000-total)]
		}
		if text == "" {
			break
		}
		ids = append(ids, id)
		b.WriteString("\n[")
		b.WriteString(id)
		b.WriteString("]")
		if item.Kind != "" {
			b.WriteString(" (")
			b.WriteString(item.Kind)
			b.WriteString(")")
		}
		if item.Title != "" {
			b.WriteString(" ")
			b.WriteString(item.Title)
		}
		b.WriteString("\n")
		b.WriteString(text)
		b.WriteString("\n")
		total += len(text)
	}
	return b.String(), ids
}

func generateWithOllama(ctx context.Context, model, prompt string) (string, error) {
	body, err := json.Marshal(map[string]any{"model": model, "prompt": prompt, "stream": false})
	if err != nil {
		return "", err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, ollamaAPIBase()+"/generate", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		raw, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		message := strings.TrimSpace(string(raw))
		if message == "" {
			message = resp.Status
		}
		return "", errors.New(message)
	}
	var payload ollamaGenerateResponse
	if err := json.NewDecoder(io.LimitReader(resp.Body, 8<<20)).Decode(&payload); err != nil {
		return "", err
	}
	answer := strings.TrimSpace(payload.Response)
	if answer == "" {
		return "", errors.New("Ollama returned an empty response")
	}
	return answer, nil
}

type store struct {
	mu   sync.Mutex
	path string
}

func (s *store) readAll() map[string]string {
	data := map[string]string{}
	raw, err := os.ReadFile(s.path)
	if err != nil {
		return data
	}
	if json.Unmarshal(raw, &data) != nil {
		return map[string]string{}
	}
	return data
}

func (s *store) get(key string) (string, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	value, ok := s.readAll()[key]
	return value, ok
}

func (s *store) set(key, value string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	data := s.readAll()
	data[key] = value
	raw, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(s.path), 0o755); err != nil {
		return err
	}
	temp := s.path + ".tmp"
	if err := os.WriteFile(temp, raw, 0o600); err != nil {
		return err
	}
	return os.Rename(temp, s.path)
}

func dataDir() (string, error) {
	if value := strings.TrimSpace(os.Getenv("COVENANT_DATA_DIR")); value != "" {
		return value, nil
	}
	if runtime.GOOS == "windows" {
		if value := strings.TrimSpace(os.Getenv("LOCALAPPDATA")); value != "" {
			return filepath.Join(value, "Covenant Library Data"), nil
		}
	}
	base, err := os.UserConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, "Covenant Library Data"), nil
}

func downloadsDir() string {
	if value := strings.TrimSpace(os.Getenv("COVENANT_EXPORT_DIR")); value != "" {
		return value
	}
	home, _ := os.UserHomeDir()
	if home == "" {
		return "."
	}
	return filepath.Join(home, "Downloads", "Covenant Library")
}

func safeFilename(name string) string {
	name = filepath.Base(strings.TrimSpace(name))
	if name == "." || name == "" {
		name = "covenant-library-export.txt"
	}
	replacer := strings.NewReplacer("<", "-", ">", "-", ":", "-", `"`, "-", "/", "-", `\\`, "-", "|", "-", "?", "-", "*", "-")
	name = strings.TrimSpace(replacer.Replace(name))
	if !strings.HasSuffix(strings.ToLower(name), ".txt") {
		name += ".txt"
	}
	return name
}

func nativeRequestAllowed(r *http.Request) bool {
	host := strings.ToLower(r.Host)
	if !(strings.HasPrefix(host, "127.0.0.1:") || strings.HasPrefix(host, "localhost:")) {
		return false
	}
	if strings.EqualFold(r.Header.Get("Sec-Fetch-Site"), "cross-site") {
		return false
	}
	if origin := strings.TrimSpace(r.Header.Get("Origin")); origin != "" {
		expected := "http://" + r.Host
		if origin != expected {
			return false
		}
	}
	return true
}

func staticHandler(root fs.FS) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		requested := r.URL.Path
		if requested == "/" || requested == "/app" {
			http.Redirect(w, r, "/app/", http.StatusTemporaryRedirect)
			return
		}
		if requested == "/app/" {
			requested = "/app/index.html"
		}
		clean := path.Clean("/" + requested)
		rel := strings.TrimPrefix(clean, "/")
		if rel == "app/platform.js" {
			w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
			w.Header().Set("Cache-Control", "no-store")
			w.WriteHeader(http.StatusOK)
			if r.Method != http.MethodHead {
				_, _ = w.Write(platformJS)
			}
			return
		}
		file, err := root.Open(rel)
		if err != nil {
			http.NotFound(w, r)
			return
		}
		defer file.Close()
		info, err := file.Stat()
		if err != nil || info.IsDir() {
			http.NotFound(w, r)
			return
		}
		ext := path.Ext(rel)
		ctype := mime.TypeByExtension(ext)
		if ctype == "" {
			switch ext {
			case ".webp":
				ctype = "image/webp"
			case ".json":
				ctype = "application/json; charset=utf-8"
			default:
				ctype = "application/octet-stream"
			}
		}
		w.Header().Set("Content-Type", ctype)
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.Header().Set("Referrer-Policy", "no-referrer")
		w.Header().Set("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'")
		w.WriteHeader(http.StatusOK)
		if r.Method != http.MethodHead {
			_, _ = io.Copy(w, file)
		}
	}
}

func openBrowser(url string) error {
	if os.Getenv("COVENANT_NO_BROWSER") == "1" {
		return nil
	}
	switch runtime.GOOS {
	case "windows":
		return exec.Command("rundll32", "url.dll,FileProtocolHandler", url).Start()
	case "darwin":
		return exec.Command("open", url).Start()
	default:
		return exec.Command("xdg-open", url).Start()
	}
}

func main() {
	dir, err := dataDir()
	if err != nil {
		log.Fatal(err)
	}
	storage := &store{path: filepath.Join(dir, "storage.json")}
	runtimeFS, err := zip.NewReader(bytes.NewReader(runtimeZip), int64(len(runtimeZip)))
	if err != nil {
		log.Fatal(err)
	}

	mux := http.NewServeMux()
	quitRequested := make(chan struct{})
	var quitOnce sync.Once
	mux.HandleFunc("/__covenant/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = json.NewEncoder(w).Encode(map[string]any{"app": "Covenant Library", "adapter": "windows", "build": buildID, "ok": true})
	})
	mux.HandleFunc("/__covenant/ai/status", func(w http.ResponseWriter, r *http.Request) {
		if !nativeRequestAllowed(r) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}
		if r.Method != http.MethodGet {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		ctx, cancel := context.WithTimeout(r.Context(), 3*time.Second)
		defer cancel()
		models, err := ollamaModels(ctx)
		if err != nil {
			_ = json.NewEncoder(w).Encode(map[string]any{"available": false, "ready": false, "models": []string{}, "selectedModel": "", "defaultModel": "llama3.2:3b", "provider": "ollama", "endpoint": ollamaAPIBase(), "message": "Ollama is not reachable on this PC."})
			return
		}
		selected := preferredModel(models)
		_ = json.NewEncoder(w).Encode(map[string]any{"available": true, "ready": len(models) > 0, "models": models, "selectedModel": selected, "defaultModel": "llama3.2:3b", "provider": "ollama", "endpoint": ollamaAPIBase(), "message": "Local Ollama is available."})
	})
	mux.HandleFunc("/__covenant/ai/ask", func(w http.ResponseWriter, r *http.Request) {
		if !nativeRequestAllowed(r) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var payload aiAskRequest
		if err := json.NewDecoder(io.LimitReader(r.Body, 2<<20)).Decode(&payload); err != nil {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "Invalid local AI request."})
			return
		}
		payload.Question = strings.TrimSpace(payload.Question)
		if payload.Question == "" {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "A study question is required."})
			return
		}
		models, err := ollamaModels(r.Context())
		if err != nil || len(models) == 0 {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusServiceUnavailable)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "Ollama is not running or has no installed local model."})
			return
		}
		model := strings.TrimSpace(payload.Model)
		if model == "" {
			model = preferredModel(models)
		}
		if !modelInstalled(models, model) {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "The selected Ollama model is not installed."})
			return
		}
		prompt, sourceIDs := buildStudyPrompt(payload.Question, payload.Context)
		if len(sourceIDs) == 0 {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusBadRequest)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "No local Covenant Library grounding material was supplied."})
			return
		}
		answer, err := generateWithOllama(r.Context(), model, prompt)
		if err != nil {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusBadGateway)
			_ = json.NewEncoder(w).Encode(map[string]any{"error": "Local Ollama generation failed: " + err.Error()})
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_ = json.NewEncoder(w).Encode(map[string]any{"response": answer, "answer": answer, "model": model, "sources": sourceIDs})
	})
	mux.HandleFunc("/__covenant/storage", func(w http.ResponseWriter, r *http.Request) {
		if !nativeRequestAllowed(r) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}
		key := r.URL.Query().Get("key")
		if key == "" || len(key) > 256 {
			http.Error(w, "Invalid key", http.StatusBadRequest)
			return
		}
		switch r.Method {
		case http.MethodGet:
			value, ok := storage.get(key)
			if !ok {
				http.NotFound(w, r)
				return
			}
			w.Header().Set("Content-Type", "text/plain; charset=utf-8")
			_, _ = io.WriteString(w, value)
		case http.MethodPut:
			body, err := io.ReadAll(io.LimitReader(r.Body, 64<<20))
			if err != nil {
				http.Error(w, "Read failed", http.StatusBadRequest)
				return
			}
			if err := storage.set(key, string(body)); err != nil {
				http.Error(w, "Save failed", http.StatusInternalServerError)
				return
			}
			w.WriteHeader(http.StatusNoContent)
		default:
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	})
	mux.HandleFunc("/__covenant/quit", func(w http.ResponseWriter, r *http.Request) {
		if !nativeRequestAllowed(r) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		_, _ = io.WriteString(w, `{"ok":true,"message":"Covenant Library is closing"}`)
		quitOnce.Do(func() { close(quitRequested) })
	})
	mux.HandleFunc("/__covenant/export", func(w http.ResponseWriter, r *http.Request) {
		if !nativeRequestAllowed(r) {
			http.Error(w, "Forbidden", http.StatusForbidden)
			return
		}
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}
		body, err := io.ReadAll(io.LimitReader(r.Body, 64<<20))
		if err != nil {
			http.Error(w, "Read failed", http.StatusBadRequest)
			return
		}
		dir := downloadsDir()
		if err := os.MkdirAll(dir, 0o755); err != nil {
			http.Error(w, "Export directory failed", http.StatusInternalServerError)
			return
		}
		target := filepath.Join(dir, safeFilename(r.URL.Query().Get("filename")))
		if err := os.WriteFile(target, body, 0o644); err != nil {
			http.Error(w, "Export failed", http.StatusInternalServerError)
			return
		}
		_, _ = io.WriteString(w, target)
	})
	mux.HandleFunc("/", staticHandler(runtimeFS))

	address := defaultAddress
	if value := strings.TrimSpace(os.Getenv("COVENANT_ADDRESS")); value != "" {
		address = value
	}
	listener, err := net.Listen("tcp", address)
	if err != nil {
		probe := "http://" + address + "/__covenant/health"
		client := http.Client{Timeout: 700 * time.Millisecond}
		if response, probeErr := client.Get(probe); probeErr == nil {
			var info map[string]any
			decodeErr := json.NewDecoder(response.Body).Decode(&info)
			response.Body.Close()
			if decodeErr == nil && response.StatusCode == http.StatusOK && info["app"] == "Covenant Library" && info["adapter"] == "windows" && info["build"] == buildID {
				_ = openBrowser("http://" + address + "/app/")
				return
			}
		}
		if address == defaultAddress {
			listener, err = net.Listen("tcp", "127.0.0.1:0")
		}
		if err != nil {
			log.Fatal(errors.New("Covenant Library could not bind a local loopback port"))
		}
	}
	defer listener.Close()

	exe, _ := os.Executable()
	if raw, err := os.ReadFile(exe); err == nil {
		sum := sha256.Sum256(raw)
		log.Printf("Covenant Library Windows adapter %s", hex.EncodeToString(sum[:8]))
	}
	url := "http://" + listener.Addr().String() + "/app/"
	log.Printf("Covenant Library: %s", url)
	if err := openBrowser(url); err != nil {
		log.Printf("Open this address in a browser: %s", url)
	}
	server := &http.Server{Handler: mux, ReadHeaderTimeout: 5 * time.Second}
	go func() {
		<-quitRequested
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		defer cancel()
		_ = server.Shutdown(ctx)
	}()
	if err := server.Serve(listener); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
}
